### PR TITLE
READY FOR DEPLOYING

### PR DESCRIPTION
**Pull request by adanielpincab**
Modified Setup.py and added build distribution.

Please, check if everything is ok in Setup.py, I may had made a typo.
Oh, and add your mail if you want to. If not, erase the commented line of the mail in Setup.py

### CODE REVIEW

**Comment by Pineapple6** [comment]
#11

**Comment by neizod** [comment]
Do we really need to put `build/`, `dist/` and `...egg-info/` directories into git? Isn't it auto-generate by running `python setup.py build`?

**Comment by Pineapple6** [comment]
Well, I think you're right, but I'm not really sure.
We could try to release it without those folders.

**Comment by Pineapple6** [comment]
Ok, I'll modify it.
But before release it, the distribution versions have to be created.

**Comment by adanielpincab** [comment]
Now only Setup.py has changed.
To deploy it, you'll have to:
* Install the necesary modules for packaging `python -m pip install --user --upgrade setuptools wheel`
* Generate the packaged distribution (/dist) `python setup.py sdist bdist_wheel`
* Install twine `python -m pip install --user --upgrade twine`
* Release the distribution packages to Test PyPI `twine upload --repository-url https://test.pypi.org/legacy/ dist/*` (You'll be asked for your user and password of your Test PyPI account. You can create an account [here](https://test.pypi.org/account/register/))
* Install the package for testing it `python -m pip install --index-url https://test.pypi.org/simple/ extmath`
* Once you have checked that everything is ok, you can release it to the real PyPI. You'll have to run the sabe command, but without the Test PyPI API: `twine upload dist/*`
* Once you run this command, you'll deploy the pakage to the real PyPI, ready to use! :smile:

**Pull request merged**
